api/urls.py
from django.urls import path, include
from knox import views as knox_views
from . import views

app_name = 'api'

urlpatterns = [
    path('auth/logout/', knox_views.LogoutView.as_view(), name='logout'),
    path('auth/login/', views.LoginAPI, name='login'),
    path('auth/register/', views.RegisterAPI, name='register'),
    path('auth/change_password/', views.Change_PasswordAPI, name='changePassword'),
    path('profile/', views.ProfileSiswaAPI, name='profile'),
    path('profile/berkas/', views.UploadBerkasAPI, name='berkas'),
    path('profile/pengajuan/', views.PengajuanAPI, name='pengajuan'),
    path('list_events/', views.ListKegiatanAPI, name='event'),
    path('notifikasi/', views.NotifikasiAPI, name='notifikasi'),
    path('sekolah/', views.SekolahAPI, name='sekolah'),
    path('siswa/<int:nis>', views.ProfileAPI, name='profileAPI'),
    path('pengumuman/', views.Pengumuman_LolosAPI, name='pengumumanAPIRoot'),
    path('pengumuman/<sort>', views.Pengumuman_LolosAPI, name='pengumumanAPI'),
]

page_admin/urls.py
from django.urls import path, include
from . import views
from . import ajax
from page_siswa.views import redirect_sites
app_name = 'admin_page'

urlpatterns = [
    path('', redirect_sites, name='rd'),
    path('home/', views.homepage, name='home'),
    path('list_siswa/', views.listsiswa, name='list_siswa'),
    path('seleksi/', views.pageSeleksi, name='seleksi'),
    path('seleksi/<data>', views.tabelSeleksi2, name='list_seleksi'),
    path('proses_seleksi/', views.prosesSeleksi, name='proses_seleksi'),
    path('daftar_ulang/', views.daftar_ulang, name='daftar_ulang'),
    path('events/', views.events, name='events'),
    path('setting/', views.setting_ppdb, name='setting'),
    path('ajax/list_siswa', ajax.list_siswa, name='ajax_list_siswa'),
    path('ajax/pembagian_kuota', ajax.pembagian_kuota, name='ajax_pembagian'),
    path('ajax/get_siswa_seleksi', ajax.getSiswaSeleksi, name='ajax_seleksi_siswa'),
    path('ajax/check_password', ajax.check_password, name='ajax_check_password'),
    path('ajax/new_password', ajax.new_password, name='ajax_new_password'),
    path('ajax/reset_tahun_ajaran', views.tahunAjaranBaru, name='ajax_reset_tahun')
]

page_siswa/urls.py
from django.urls import path
from . import views
from . import ajax
from page_admin import ajax as ajax_admin
app_name = 'siswa'

urlpatterns = [
    path('', views.redirect_sites, name='rd'),
    path('home/', views.homepage, name='home'),
    path('login/', views.login_views, name='login'),
    path('logout/', views.logout_views, name='logout'),
    path('register/', views.register_views, name='register'),
    path('tahapan_pendaftaran/', views.tahapan_pendaftaran_views, name='tahapan_pendaftaran'),
    path('proses_pengajuan_pendaftaran', views.proses_ajukan_pendaftaran, name='proses_pengajuan'),
    path('ganti_password/', views.ganti_password, name='ganti_password'),
    path('informasi_pendaftaran/', views.informasi_pendaftaran, name='informasi_pendaftaran'),
    path('pengumuman/', views.pengumuman_penerimaan, name='pengumuman'),
    path('success', views.success, name='success'),
    path('ajax/get_provinsi', ajax.get_provinsi, name='ajax_provinsi'),
    path('ajax/get_kota/<int:id>', ajax.get_kota, name='ajax_kota'),
    path('ajax/get_kecamatan/<int:id>', ajax.get_kecamatan, name='ajax_kecamatan'),
    path('ajax/get_kelurahan/<int:id>', ajax.get_kelurahan, name='ajax_kelurahan'),
]

web_pendaftaran/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('page_siswa.urls')),
    path('admin/', include('page_admin.urls')),
    path('api/', include('api.urls')),
    # path('admin/', admin.site.urls)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

page_admin/models.py
from django.db import models

# Create your models here.

page_admin/views.py
import json

from django.shortcuts import render, redirect
from django.db.models import F, Q, Avg
from django.contrib import messages
from django.core.paginator import Paginator
from django.http import JsonResponse
from page_siswa.views import convert_date
from page_siswa.models import Siswa, list_events, list_notifikasi, sekolah
# Create your views here.


def homepage(request):
    if request.user.is_authenticated and not request.user.is_staff:
        return redirect('siswa:home')
    elif not request.user.is_authenticated:
        return redirect('siswa:login')
    data_sekolah = sekolah.objects.first()
    setting = False
    if data_sekolah.nama == '' or data_sekolah.alamat == '' or data_sekolah.daya_tampung == 0:
        setting = True
    siswa = Siswa.object.all()
    laki = siswa.filter(jenis_kelamin='L')
    perempuan = siswa.filter(jenis_kelamin='P')
    status = {
        'identitas': len(siswa.filter(status=0)),
        'upload_berkas': len(siswa.filter(status=1)),
        'verifikasi': len(siswa.filter(status=6)),
        'gagal_verifikasi': len(siswa.filter(status=7)),
        'jalur_zonasi': len(siswa.filter(jalur_pendaftaran='Zonasi')),
        'jalur_afirmasi': len(siswa.filter(jalur_pendaftaran='Afirmasi')),
        'jalur_perpindahan': len(siswa.filter(jalur_pendaftaran='Perpindahan OrangTua')),
        'jalur_prestasi': len(siswa.filter(jalur_pendaftaran='Prestasi')),
    }
    data = {'jumlah': len(siswa), 'laki': len(laki), 'perempuan': len(perempuan),
            'status': status}
    # print(data)
    return render(request=request,
                  template_name='page_admin/beranda.html',
                  context={'data': data, 'active': 'beranda', 'setting': setting})


def listsiswa(request):
    if request.user.is_authenticated and not request.user.is_staff:
        return redirect('siswa:home')
    elif not request.user.is_authenticated:
        return redirect('siswa:login')
    data_sekolah = sekolah.objects.first()
    setting = False
    if data_sekolah.nama == '' or data_sekolah.alamat == '' or data_sekolah.daya_tampung == 0:
        setting = True
    siswa = Siswa.object.all()
    list_siswa = Siswa.object.order_by('nis')
    paginator = Paginator(list_siswa, 7)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    if request.method == 'POST':
        alasan = request.POST.get('alasan')
        siswa = Siswa.object.get(nis=request.POST.get('nis_siswa'))
        list_notifikasi.objects.create(siswa=siswa, notifikasi=alasan)
        messages.success(request, f'Pesan berhasil dikirimkan')
    return render(request=request,
                  template_name='page_admin/tabelSiswa.html',
                  context={'list_siswa': page_obj, 'active': 'list', 'setting': setting})


def pageSeleksi(request):
    data_sekolah = sekolah.objects.first()
    if request.user.is_authenticated and not request.user.is_staff:
        return redirect('siswa:home')
    elif not request.user.is_authenticated:
        return redirect('siswa:login')
    if data_sekolah.status_pendaftaran != 2:
        messages.error(
            request, f'Ubah Status PPDB di Setting PPDB, untuk memulai Proses Seleksi Siswa.')
        return redirect('admin_page:setting')
    data_sekolah = sekolah.objects.first()
    data_siswa = Siswa.object.all()
    setting = False
    if data_sekolah.nama == '' or data_sekolah.alamat == '' or data_sekolah.daya_tampung == 0:
        setting = True
    zonasi = {
        'jumlah': len(data_siswa.filter(status=10)),
        'kuota': json.loads(data_sekolah.pembagian_kuota())['zonasi']
    }
    afirmasi = {
        'jumlah': len(data_siswa.filter(status=11)),
        'kuota': json.loads(data_sekolah.pembagian_kuota())['afirmasi']
    }
    perpindahan = {
        'jumlah': len(data_siswa.filter(status=12)),
        'kuota': json.loads(data_sekolah.pembagian_kuota())['perpindahan']
    }
    prestasi = {
        'jumlah': len(data_siswa.filter(status=13)),
        'kuota': json.loads(data_sekolah.pembagian_kuota())['prestasi']
    }
    tolak = {
        'jumlah': len(data_siswa.filter(status=7)),
        'kuota': data_sekolah.sisa_prestasi
    }
    # print(tolak)
    return render(request=request,
                  template_name='page_admin/seleksi_siswa.html',
                  context={'active': 'seleksi', 'data': [zonasi, afirmasi, perpindahan, prestasi]})


def tabelSeleksi2(request, data):
    data_sekolah = sekolah.objects.first()
    if request.user.is_authenticated and not request.user.is_staff:
        return redirect('siswa:home')
    elif not request.user.is_authenticated:
        return redirect('siswa:login')
    if data_sekolah.status_pendaftaran != 2:
        messages.error(
            request, f'Ubah Status PPDB di Setting PPDB, untuk memulai Proses Seleksi Siswa.')
        return redirect('admin_page:setting')
    data_sekolah = sekolah.objects.first()
    first_time = False
    seleksi = {
        'nama': data.title()
    }
    alamat_sekolah = json.loads(data_sekolah.split_alamat())
    setting = False
    if data_sekolah.nama == '' or data_sekolah.alamat == '' or data_sekolah.daya_tampung == 0:
        setting = True
    if data == 'zonasii' or data == 'afirmasii' or data == 'perpiindahan' or data == 'prestasii':
        first_time = True
    if data == 'zonasi' or data == 'zonasii':
        list_siswa = Siswa.object.filter(status=10).annotate(
            avg=(F('nilai_matematika') + F('nilai_ipa') + F('nilai_indonesia') + F('nilai_inggris'))/4).order_by('-avg')
        if len(list_siswa) == 0:
            messages.success(
                request, f'Seleksi Untuk Jalur Zonasi telah Di selesaikan')
            return redirect('admin_page:seleksi')
        seleksi['kuota'] = data_sekolah.sisa_zonasi
        seleksi['jumlah_siswa'] = len(list_siswa)
        if (data_sekolah.sisa_zonasi - len(list_siswa)) >= 0:
            seleksi['sisa_kuota'] = data_sekolah.sisa_zonasi - len(list_siswa)
        else:
            seleksi['sisa_kuota'] = 0
        kab = []
        kec = []
        des = []
        for x in list_siswa:
            if x.get_desa_siswa() == alamat_sekolah['desa']:
                des.append(x)
            elif x.get_kecamatan_siswa() == alamat_sekolah['kecamatan']:
                kec.append(x)
            elif x.get_kabupaten_siswa() == alamat_sekolah['kabupaten']:
                kab.append(x)
        list_siswa = {}
        list_siswa['kabupaten'] = kab
        list_siswa['kecamatan'] = kec
        list_siswa['desa'] = des
    elif data == 'afirmasi' or data == 'afirmasii':
        list_siswa = Siswa.object.filter(status=11).annotate(
            avg=(F('nilai_matematika') + F('nilai_ipa') + F('nilai_indonesia') + F('nilai_inggris'))/4).order_by('-avg')
        if len(list_siswa) == 0:
            messages.success(
                request, f'Seleksi Untuk Jalur Afirmasi telah Di selesaikan')
            return redirect('admin_page:seleksi')
        seleksi['kuota'] = data_sekolah.sisa_afirmasi
        seleksi['jumlah_siswa'] = len(list_siswa)
        if (data_sekolah.sisa_afirmasi - len(list_siswa)) >= 0:
            seleksi['sisa_kuota'] = data_sekolah.sisa_afirmasi - \
                len(list_siswa)
        else:
            seleksi['sisa_kuota'] = 0
    elif data == 'perpindahan' or data == 'perpiindahan':
        list_siswa = Siswa.object.filter(status=12).annotate(
            avg=(F('nilai_matematika') + F('nilai_ipa') + F('nilai_indonesia') + F('nilai_inggris'))/4).order_by('-avg')
        if len(list_siswa) == 0:
            messages.success(
                request, f'Seleksi Untuk Jalur Perpindahan Orang Tua telah Di selesaikan')
            return redirect('admin_page:seleksi')
        seleksi['kuota'] = data_sekolah.sisa_perpindahan
        seleksi['jumlah_siswa'] = len(list_siswa)
        if (data_sekolah.sisa_perpindahan - len(list_siswa)) >= 0:
            seleksi['sisa_kuota'] = data_sekolah.sisa_perpindahan - \
                len(list_siswa)
        else:
            seleksi['sisa_kuota'] = 0
    elif data == 'prestasi' or data == 'prestasii':
        list_siswa = Siswa.object.filter(status=13).annotate(
            avg=(F('nilai_matematika') + F('nilai_ipa') + F('nilai_indonesia') + F('nilai_inggris'))/4).order_by('-avg')
        if len(list_siswa) == 0:
            messages.success(
                request, f'Seleksi Untuk Jalur Prestasi telah Di selesaikan')
            return redirect('admin_page:seleksi')
        seleksi['kuota'] = data_sekolah.sisa_prestasi
        seleksi['jumlah_siswa'] = len(list_siswa)
        if (data_sekolah.sisa_prestasi - len(list_siswa)) >= 0:
            seleksi['sisa_kuota'] = data_sekolah.sisa_prestasi - \
                len(list_siswa)
        else:
            seleksi['sisa_kuota'] = 0
    else:
        messages.error(request, f'Terjadi Kesalahan')
        return redirect('admin_page:seleksi')
    if request.method == 'POST':
        data = request.POST.get('data')
        if data == 'Zonasi' or data == 'Zonasii':
            count = seleksi['kuota']
            for x in list_siswa['desa']:
                if(count > 0):
                    # print('desa')
                    count -= 1
                    x.status = 5
                    x.save()
                else:
                    x.status = 7
                    x.save()
            for x in list_siswa['kecamatan']:
                if(count > 0):
                    # print('kecamatan')
                    count -= 1
                    x.status = 5
                    x.save()
                else:
                    x.status = 7
                    x.save()
            for x in list_siswa['kabupaten']:
                if(count > 0):
                    # print('kabupaten')
                    count -= 1
                    x.status = 5
                    x.save()
                else:
                    x.status = 7
                    x.save()
            if count > 0:

page_admin/templates/page_admin/base.html
<!DOCTYPE html>
<html>

<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>PPDB Online | {% block judul%}{% endblock %}</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css'%}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'css/adminlte/adminlte.min.css' %}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/css/tempusdominus-bootstrap-4.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
    {% block header %}

    {% endblock %}
</head>

<body class="hold-transition sidebar-mini layout-boxed">
    <!-- Site wrapper -->
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
                </li>
            </ul>

            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a href="{% url 'siswa:logout' %}" class="nav-link btn btn-default btn-flat"
                        style="cursor: pointer;">Logout</a>
                </li>
            </ul>
        </nav>
        <!-- /.navbar -->

        <!-- Main Sidebar Container -->

        {% include 'page_admin/sidebar.html' %}

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                {% include 'page_siswa/messages.html' %}
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-12">
                            <h1 class="text-center">{{judul}}</h1>
                        </div>
                    </div>
                </div><!-- /.container-fluid -->
            </section>

            <!-- Main content -->
            <section class="content">
                {% block konten %}

                {% endblock %}
            </section>
            <!-- /.content -->

        </div>
        <!-- /.content-wrapper -->
        <div class="modal fade bd-example-modal-sm" id="modalSetting" tabindex="-1" role="dialog"
            aria-labelledby="mySmallModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <div class="modal-title">
                            <h4 class="text-center">Peringatan</h4>
                        </div>
                    </div>
                    <div class="modal-body">
                        <h2>Settingan PPDB belum dilengkapi, Silahkan Lengkapi Terlebih Dahulu.</h2>
                    </div>
                    <div class="modal-footer">
                        <a href="{% url 'admin_page:setting' %}">
                            <button type="button" form="formKuota" class="btn btn-primary">Ya</button>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ./wrapper -->

    <!-- jQuery -->
    <script src="{% static 'plugins/jquery/jquery.min.js'%}"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
    <script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/js/tempusdominus-bootstrap-4.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- ChartJS -->
    <script src="{% static 'plugins/chart.js/Chart.min.js'%}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'js/adminlte/adminlte.js'%}"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <!-- <script src="{% static 'js/adminlte/pages/dashboard.js'%}"></script> -->
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'js/adminlte/demo.js' %}"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
        integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
        crossorigin="anonymous"></script>

    <script type="text/javascript">
        $(function () {
            $('#datetimepicker5').datetimepicker({
                format: 'DD-MM-YYYY'
            });
        });
    </script>
    {% if setting %}
    <script>
        $('#modalSetting').modal({ backdrop: 'static', keyboard: false });
    </script>
    {% endif %}

    <script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>
    {% block script %}

    {% endblock %}

</body>

</html>

page_admin/templates/page_admin/sidebar.html
{% load static %}

<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{% url 'siswa:login' %}" class="brand-link">
        <img src="https://i.postimg.cc/qqfG9SZm/Admin-LTELogo.png" alt="AdminLTE Logo"
            class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">PPDB Online</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{% static 'assets/Network-Profile.png'%}" class="img-circle elevation-2"
                    alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">{{request.user.get_full_name}}</a>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-item has-treeview">
                    <a href="{% url 'admin_page:home'%}" class="nav-link {%if active == 'beranda'%}active{%endif%}">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>Beranda</p>
                    </a>
                </li>
                <li class="nav-item has-treeview">
                    <a href="{% url 'admin_page:list_siswa'%}" class="nav-link {%if active == 'list'%}active{%endif%}">
                        <i class="nav-icon fas fa-copy"></i>
                        <p>List Siswa</p>
                    </a>
                </li>
                <li class="nav-item has-treeview">
                    <a href="{% url 'admin_page:seleksi'%}" class="nav-link {%if active == 'seleksi'%}active{%endif%}">
                        <i class="nav-icon fas fa-clipboard-check"></i>
                        <p>Seleksi Siswa</p>
                    </a>
                </li>
                <li class="nav-item has-treeview">
                    <a href="{% url 'admin_page:daftar_ulang'%}"
                        class="nav-link {%if active == 'daftar_ulang'%}active{%endif%}">
                        <i class="nav-icon fas fa-clipboard-list"></i>
                        <p>Daftar Ulang</p>
                    </a>
                </li>
                <li class="nav-item has-treeview">
                    <a href="{% url 'admin_page:events'%}" class="nav-link {%if active == 'events'%}active{%endif%}">
                        <i class="nav-icon fas fa-calendar-day"></i>
                        <p>Jadwal Events</p>
                    </a>
                </li>
                <li class="nav-item has-treeview">
                    <a href="{% url 'admin_page:setting'%}" class="nav-link {%if active == 'setting'%}active{%endif%}">
                        <i class="nav-icon fas fa-cog"></i>
                        <p>Setting PPDB</p>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>

page_admin/templates/page_admin/tabel_base.html
{% for siswa in list_siswa%}
<tr>
    <td class="text-center align-middle">{{siswa.nis}}</td>
    <td class="align-middle text-center">{{siswa.user.get_full_name}}</td>
    <td class="align-middle text-center">{{siswa.nilai_indonesia}}</td>
    <td class="align-middle text-center">{{siswa.nilai_inggris}}</td>
    <td class="align-middle text-center">{{siswa.nilai_matematika}}</td>
    <td class="align-middle text-center">{{siswa.nilai_ipa}}</td>
    <td class="align-middle text-center">{{siswa.check_rata_rata}}</td>
    <th class="manualSeleksi">
        <button class="btn btn-primary" style="width: 100px;"
            onclick="openModalTerima('{{siswa.nis}}','{{siswa.user.get_full_name}}')">Terima</button>
        <button class="btn btn-danger mt-2" style="width: 100px;"
            onclick="openModalTolak('{{siswa.nis}}','{{siswa.user.get_full_name}}')">Tolak</button>
        <button class="btn btn-success mt-2" style="width: 100px;" onclick="openDetail('{{siswa.nis}}')">Detail</button>
    </th>
</tr>
{% endfor %}
<tr>
    <td class="text-center align-middle" colspan="8">
        Tidak Ada Siswa yang perlu diseleksi
    </td>
</tr>

page_admin/templates/page_admin/tabel_lainnya.html
{% if list_siswa %}
{% for siswa in list_siswa %}
<tr>
    <td class="align-middle text-center">{{forloop.counter}}</td>
    <td class="text-center align-middle">{{siswa.nis}}</td>
    <td class="align-middle text-center">{{siswa.user.get_full_name}}</td>
    <td class="align-middle text-center">{{siswa.nilai_indonesia}}</td>
    <td class="align-middle text-center">{{siswa.nilai_inggris}}</td>
    <td class="align-middle text-center">{{siswa.nilai_matematika}}</td>
    <td class="align-middle text-center">{{siswa.nilai_ipa}}</td>
    <td class="align-middle text-center">{{siswa.check_rata_rata}}</td>
    <th class="manualSeleksi">
        <button class="btn btn-danger mt-2" style="width: 100px;"
            onclick="openModalTolak('{{siswa.nis}}','{{siswa.user.get_full_name}}')">Tolak</button>
        <button class="btn btn-success mt-2" style="width: 100px;" onclick="openDetail('{{siswa.nis}}')">Detail</button>
    </th>
</tr>
{% endfor %}
{% endif %}
{% if not list_siswa %}
<tr>
    <td class="text-center align-middle" colspan="8">
        Tidak Ada Siswa yang perlu diseleksi
    </td>
</tr>
{% endif %}